language: "en"
early_access: false
reviews:
  high_level_summary: false
  poem: false
  review_status: false
  collapse_walkthrough: false
  path_instructions:
    - path: "**/*.mdx",m
      instructions: |
        "ALWAYS review Markdown content THOROUGHLY with the following criteria:
        1. Use proper nouns in place of personal pronouns like 'We' and 'Our' to maintain consistency in communal documentation.
        2. Avoid gender-specific language and use the imperative form.
        3. Monitor capitalization for emphasis. Use **bold** for prominence instead of all caps or italics.
        4. Ensure proper nouns are capitalized in sentences.
        5. Apply the Oxford comma.
        6. Use proper title case for headers, buttons, tab names, page names, and links. Sentence case should be used for body content and short phrases, even in links.
        "
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: true
